### PR TITLE
Security updates from Dependabot

### PR DESCRIPTION
**Pull request by wojtekzyla**

### CODE REVIEW

**Review by ajasnosz — APPROVED** [review]

**Comment by ajasnosz** [comment]
Add description on what version were updated here or to release notes.

**Comment by wojtekzyla** [comment]
Updated the following dependencies from `frontend/packages/manager/package.json` and `frontend/package.json`:

- `mongodb` from "^4.8.0" to "^5.8.0"
- `axios` from "^1.6.0" to "^1.6.8"


Other updates from `yarn.lock`:

- `body-parser `from "1.20.0" to "1.20.2"
- `content-type` from "1.0.4" to "1.0.5"
- `cookie` from "0.5.0" to "0.6.0"
- `express` from "4.18.2" to "4.19.2"
- `follow-redirects` from versions "1.15.1", "1.15.2", "1.15.5" to single version "1.15.6."
- `ip` from "2.0.0" to "2.0.1"
- `qs` from "6.10.3" to "6.11.0"
- `raw-body` from "2.5.1" to "2.5.2"
- `webpack-dev-middleware` from "5.3.3" to "5.3.4"

**Pull request merged**
