### PR TITLE
fix: add unit tests to pipeline

### PR DESCRIPTION
**Pull request by wojtekzyla**
- add unit tests to pipeline

### CODE REVIEW

**Comment by omrozowicz-splunk** [comment]
image
Can we fix these warnings before merging? That will save us time on cleanup in future 😄

**Comment by wojtekzyla** [comment]
> [ ](/wojtekzyla)

fixed

**Comment by wojtekzyla** [comment]
> fixed



> image Can we fix these warnings before merging? That will save us time on cleanup in future 😄

fixed

**Review by omrozowicz-splunk — APPROVED** [review]

**Pull request merged**
